version: '3'
services:
  web1:
    image: 'eldejr/apache2'
    networks:
      - mynet 
  web2:
          #    image: 'eldejr/nginx'
    image: 'eldejr/nginx:latest'
    networks:
      - mynet
  web3:
    image: 'eldejr/apache2'
    networks:
      - mynet
  web4:
    image: 'eldejr/nginx:latest'
          #    image: 'eldejr/nginx'
    networks:
      - mynet
  lb:
    image: 'loadbalancer:v0.3'
          #    image: 'abhyuni/loadbalancer'
    volumes:
      - type: bind
        source: ./ubuntu_nginx_loadbalancer/nginx/sites-available
        target: /etc/nginx/sites-available
    networks:
      - mynet
    ports: 
      - 80:80
    depends_on:
      - web1
      - web2
      - web3
      - web4
networks:
  mynet:
